version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew --no-daemon test shadowJar
artifacts:
  files:
    - "*-all.jar"
  base-directory: build/libs
cache:
  paths:
    - '/root/.gradle/**/*'
